/*
 * Isaias Manuel Pinto Martinez
 *          29671221
 * algerninjaxdd@gmail.com
 */
package Ejer1;

import javax.swing.JOptionPane;

/**
 *
 * @author Jose Pinto
 */
public class Vista00 extends javax.swing.JFrame {

    /**
     * Creates new form Vista00
     */
    public Vista00() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnBack = new javax.swing.JButton();
        jbtnStar = new javax.swing.JButton();
        jbtnAgg = new javax.swing.JButton();
        jbtnBus = new javax.swing.JButton();
        jbtnMod = new javax.swing.JButton();
        jbtnDel = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlbMinux = new javax.swing.JLabel();
        jlbExit = new javax.swing.JLabel();
        jPOperaciones = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtEmpresa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtTlf = new javax.swing.JTextField();
        jlTlf = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtPTrabajo = new javax.swing.JTextField();
        jLEmpleo = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 150, 217)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setBackground(new java.awt.Color(255, 255, 255));
        jbtnBack.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(104, 53, 68));
        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBack_off.png"))); // NOI18N
        jbtnBack.setBorder(null);
        jbtnBack.setContentAreaFilled(false);
        jbtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBack_on.png"))); // NOI18N
        jbtnBack.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBack_on.png"))); // NOI18N
        jbtnBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBack_on.png"))); // NOI18N
        jPanel1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 110, -1, -1));

        jbtnStar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnStar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnStar.setForeground(new java.awt.Color(104, 53, 68));
        jbtnStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnStar_off.png"))); // NOI18N
        jbtnStar.setBorder(null);
        jbtnStar.setContentAreaFilled(false);
        jbtnStar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnStar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnStar_on.png"))); // NOI18N
        jbtnStar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnStar_on.png"))); // NOI18N
        jbtnStar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnStar_on.png"))); // NOI18N
        jPanel1.add(jbtnStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jbtnAgg.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAgg.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnAgg.setForeground(new java.awt.Color(104, 53, 68));
        jbtnAgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnAgg_off.png"))); // NOI18N
        jbtnAgg.setBorder(null);
        jbtnAgg.setContentAreaFilled(false);
        jbtnAgg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAgg.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnAgg_on.png"))); // NOI18N
        jbtnAgg.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnAgg_on.png"))); // NOI18N
        jbtnAgg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnAgg_on.png"))); // NOI18N
        jPanel1.add(jbtnAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 160, -1, -1));

        jbtnBus.setBackground(new java.awt.Color(255, 255, 255));
        jbtnBus.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnBus.setForeground(new java.awt.Color(104, 53, 68));
        jbtnBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBus_off.png"))); // NOI18N
        jbtnBus.setBorder(null);
        jbtnBus.setContentAreaFilled(false);
        jbtnBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBus_on.png"))); // NOI18N
        jbtnBus.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBus_on.png"))); // NOI18N
        jbtnBus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnBus_on.png"))); // NOI18N
        jPanel1.add(jbtnBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 210, -1, -1));

        jbtnMod.setBackground(new java.awt.Color(255, 255, 255));
        jbtnMod.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnMod.setForeground(new java.awt.Color(104, 53, 68));
        jbtnMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnMod_off.png"))); // NOI18N
        jbtnMod.setBorder(null);
        jbtnMod.setContentAreaFilled(false);
        jbtnMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMod.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnMod_on.png"))); // NOI18N
        jbtnMod.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnMod_on.png"))); // NOI18N
        jbtnMod.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnMod_on.png"))); // NOI18N
        jPanel1.add(jbtnMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 260, -1, -1));

        jbtnDel.setBackground(new java.awt.Color(255, 255, 255));
        jbtnDel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnDel.setForeground(new java.awt.Color(104, 53, 68));
        jbtnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnDel_off.png"))); // NOI18N
        jbtnDel.setBorder(null);
        jbtnDel.setContentAreaFilled(false);
        jbtnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnDel_on.png"))); // NOI18N
        jbtnDel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnDel_on.png"))); // NOI18N
        jbtnDel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnDel_on.png"))); // NOI18N
        jPanel1.add(jbtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 310, -1, -1));

        jbtnExit.setBackground(new java.awt.Color(255, 255, 255));
        jbtnExit.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(104, 53, 68));
        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnExit_off.png"))); // NOI18N
        jbtnExit.setBorder(null);
        jbtnExit.setContentAreaFilled(false);
        jbtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnExit_on.png"))); // NOI18N
        jbtnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnExit_on.png"))); // NOI18N
        jbtnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_btnExit_on.png"))); // NOI18N
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_User.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel8.setText("By Isaias");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 440));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbMinux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Minust.png"))); // NOI18N
        jlbMinux.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbMinux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMinuxMouseClicked(evt);
            }
        });
        jPanel3.add(jlbMinux, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jlbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Exit.png"))); // NOI18N
        jlbExit.setToolTipText("");
        jlbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbExitMouseClicked(evt);
            }
        });
        jPanel3.add(jlbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 600, 40));

        jPOperaciones.setBackground(new java.awt.Color(255, 255, 255));
        jPOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        jPOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Search_32px.png"))); // NOI18N
        jPOperaciones.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 30));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setToolTipText("");
        txtBuscar.setBorder(null);
        jPOperaciones.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 130, 30));
        jPOperaciones.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 170, 10));
        jPOperaciones.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 170, 10));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setToolTipText("");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPOperaciones.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 130, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_User_32px_1.png"))); // NOI18N
        jPOperaciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));
        jPOperaciones.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 10));

        txtEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpresa.setToolTipText("");
        txtEmpresa.setBorder(null);
        jPOperaciones.add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Trabajo_32px.png"))); // NOI18N
        jPOperaciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));
        jPOperaciones.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 10));

        txtTlf.setBackground(new java.awt.Color(255, 255, 255));
        txtTlf.setForeground(new java.awt.Color(0, 0, 0));
        txtTlf.setToolTipText("");
        txtTlf.setBorder(null);
        jPOperaciones.add(txtTlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 130, 30));

        jlTlf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Telefono_32px_1.png"))); // NOI18N
        jPOperaciones.add(jlTlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        jPOperaciones.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 10));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setToolTipText("");
        txtApellido.setBorder(null);
        jPOperaciones.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, 30));

        jLApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Idea_32px_1.png"))); // NOI18N
        jPOperaciones.add(jLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        jPOperaciones.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 170, 10));

        txtPTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        txtPTrabajo.setForeground(new java.awt.Color(0, 0, 0));
        txtPTrabajo.setToolTipText("");
        txtPTrabajo.setBorder(null);
        jPOperaciones.add(txtPTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 130, 30));

        jLEmpleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Empleo_32px_1.png"))); // NOI18N
        jPOperaciones.add(jLEmpleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPOperaciones.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 170, 10));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setToolTipText("");
        txtCorreo.setBorder(null);
        jPOperaciones.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 130, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_Correo_32px.png"))); // NOI18N
        jPOperaciones.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Apellido:");
        jPOperaciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Nombre:");
        jPOperaciones.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Puesto de trabajo:");
        jPOperaciones.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Empleo:");
        jPOperaciones.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Correo:");
        jPOperaciones.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Telefono:");
        jPOperaciones.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        jPOperaciones.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 70, -1));
        jPOperaciones.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, 10));

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.setToolTipText("");
        txtCedula.setBorder(null);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPOperaciones.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 130, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon_User_32px_1.png"))); // NOI18N
        jPOperaciones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Cedula:");
        jPOperaciones.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel24.setText("Ingrese cedula para buscar:");
        jPOperaciones.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        getContentPane().add(jPOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jlbMinuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMinuxMouseClicked
       this.setState(Vista00.ICONIFIED);
    }//GEN-LAST:event_jlbMinuxMouseClicked

    private void jlbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExitMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir?", "Salir",dialog);
        if (result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jlbExitMouseClicked

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed

    }//GEN-LAST:event_jbtnExitActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista00().setVisible(true);;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLEmpleo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPOperaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JButton jbtnAgg;
    public javax.swing.JButton jbtnBack;
    public javax.swing.JButton jbtnBus;
    public javax.swing.JButton jbtnDel;
    public javax.swing.JButton jbtnExit;
    public javax.swing.JButton jbtnMod;
    public javax.swing.JButton jbtnStar;
    private javax.swing.JLabel jlTlf;
    private javax.swing.JLabel jlbExit;
    private javax.swing.JLabel jlbMinux;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtEmpresa;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPTrabajo;
    public javax.swing.JTextField txtTlf;
    // End of variables declaration//GEN-END:variables
}
